### ISSUE TITLE
Enhancement Request: Action Group

### ISSUE THREAD

**Issue by aelana** [TriggerAu/AlternateResourcePanel#38]
Similar to how you provide a consistent interface to the staging controls (either through mouse or optional keyboard on the map) would it be possible to create a fly-out option with a list of action groups (1-0, abort, gear, lights) with the ability to edit a one line text field per item per ship (saved per ship)?

So say for example you put a button below the "Stage" button which if you press it the window expands with a list of action group text fields with a button next to each to activate the action group.

**Comment by TriggerAu** [comment]
I'm gonna close this one. I'm unsure that i can commit the time to getting it on there correctly and there will be even more UI changes with U5 soonish. Sorry I couldnt do this request
