### ISSUE TITLE
.version file pointing at wrong url

### ISSUE THREAD

**Issue by Olympic1** [TriggerAu/AlternateResourcePanel#62]
KSP-AVC can't check for new versions because the url isn't pointing to a valid .version file. Current link is
https://raw.githubusercontent.com/TriggerAu/AlternateResourcePanel/master/AlternateResourcePanel/AlternateResourcePanel.version

change it to
https://raw.githubusercontent.com/TriggerAu/AlternateResourcePanel/master/AlternateResourcePanel/KSPAlternateResourcePanel.version

**Comment by TriggerAu** [comment]
Well I obviously cocked up that part of my build script. Thanks for the heads up
