### ISSUE TITLE
Display units not working correctly

### ISSUE THREAD

**Issue by seanth** [TriggerAu/AlternateResourcePanel#71]
I am fairly certain the units showed when changing them to Tonnes or kg are not working.

Right now, the default KSP units are Liters. So setting the display to Liters works fine.

Setting the display to tonnes should take the default KSP value and multiply it by that resource's density

Setting the display to kilograms would be the same as for tonnes, by *1000

As an example, take the RT-100 solid fuel booster.

If holds 300 units of solid fuel, and has a mass of 0.75. In the VAB, it is identified as 3.0 tonnes. The density of the fuel is 0.0075 tonne/L. If you right-click on the RT-100, it says it masses 2.25 tonnes. This calculation is not 100% correct. It is the mass of the fuel alone:

(0.0075 tonne/L)*300L = 2.25 tonne. 

Add in the mass of the empty RT-100 as listed by the part's cfg (0.75tonne) and you get the total mass of 3.0 tonne (as reported by the little build helper in the SPH and VAB)

To show the tonnes for the RT-100:
(resource density)/(amount or resource present in stock KSP units)=tonnes
To show the kilograms for the RT-100:
[(resource density)/(amount or resource present in stock KSP units)]*1000=kilograms
To show the liters for the RT-100:
Just slap a "L" on the end (like is currently done)

**Comment by TriggerAu** [comment]
Integrated these this morning and tests fine
