### ISSUE TITLE
Resource Transfer allowed before R&D is upgraded to right version in Career

### ISSUE THREAD

**Issue by TriggerAu** [TriggerAu/AlternateResourcePanel#72]

**Comment by TomFyuri** [comment]
I can confirm this. Also some docking things (as noted in description of such docking things) disallow resource transfer through them. Using this plugin I could transfer resources without problem... Such cheating. :D

**Comment by TriggerAu** [comment]
Career based issue is resolved . Will raise new item for part issue - this commit: 8ad4b258db32cace76e7a9ad473221693898768d
