### ISSUE TITLE
Autostaging staging decouplers for full fuel tanks.

### ISSUE THREAD

**Issue by QuickBASIC** [TriggerAu/AlternateResourcePanel#73]
For some reason, autostaging is dumping the outer six fuel tanks while still full (they don't have any engines on them, but they feed the inner tank.

![](http://i.imgur.com/gh4bFCa.png)

**Comment by TriggerAu** [comment]
Do you mind sharing the craft file with me? will make it easier to look into

**Comment by QuickBASIC** [comment]
[.craft file](https://drive.google.com/file/d/0B056bO_lKRWJNG5FWVZFOC1FYk0/view?usp=sharing)

**Comment by TriggerAu** [comment]
Ta, will look into it this weekend

**Comment by TriggerAu** [comment]
Got to the bottom of this one I think. The autostaging is based on when engines run out then it stages - the fact that these tanks have no attacjhed engines is causing some miscalcs. I can repl it on a much smaller vessel - working out what's possible now

**Comment by TriggerAu** [comment]
Found and fixed. The codes commited and the fix will be in the next version
