### ISSUE TITLE
Move config cfg files to PluginData

### ISSUE THREAD

**Issue by RealKolago** [TriggerAu/AlternateResourcePanel#87]
ModuleManger builds up a new cache file on every start when changing config cfg files are not stored in a PluginData folder.

GameData\TriggerTech\KSPAlternateResourcePanel\settings.cfg

-> GameData\TriggerTech\KSPAlternateResourcePanel\PluginData\settings.cfg

**Comment by TriggerAu** [comment]
Done by #86 , be there soon
